---
language: node_js
os:
  - linux
  - osx
node_js:
  - 10
  - 12
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn install
script:
  - AST_COMPARE=1 yarn test -- --runInBand
  - yarn codecov
